source 'https://rubygems.org'

gem 'chronic'
gem 'fiscali'
gem 'google-analytics-admin-v1alpha'
gem 'google-analytics-data-v1beta'
gem 'google-api-client'
gem 'mail'
gem 'mechanize'
gem 'spreadsheet'
gem 'thor'
